add some error checking

diff --git a/alarmsync b/alarmsync
--- a/alarmsync
+++ b/alarmsync
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-REPOPATH=./upload
+REPOPATH=./update
 #MIRROR=http://upstream.example.com
 MIRROR=http://fl.us.mirror.archlinuxarm.org
 #ARCH=armv7h
@@ -26,14 +26,25 @@ get_arch() {
 # ${MIRROR/${ARCH}
 # http://upstream.a10g.com/archv7h
 
+check_wget() {
+	if ! [ -x "$(command -v wget)" ]; then
+		echo 'Error: wget is not installed.' >&2
+		exit 1
+	fi
+}
 check_mirror() {
 	REMOTE=$(curl -sS ${MIRROR}/${ARCH}/sync)
-	LOCAL=$(cat ${REPOPATH}/current/${ARCH}/sync)
- 	if [ "$REMOTE" = "$LOCAL" ]; then
-		echo "No new updates."
-		return 0
+	if [[ -d "${REPOPATH}/current" ]]; then
+		LOCAL=$(cat ${REPOPATH}/current/${ARCH}/sync)
+ 		if [ "$REMOTE" = "$LOCAL" ]; then
+			echo "No new updates."
+			return 0
+		else
+			echo "Updates available."
+			return 1
+		fi
 	else
-		echo "Updates available."
+		echo "No -current found. Updates probably available."
 		return 1
 	fi
 }
@@ -60,6 +71,13 @@ sync_mirror() {
 #	echo "Repointing -current to ${DATE}..."
 #	ln -s ${REPOPATH}/${DATE} ${REPOPATH}/current
 #}
+
+check_repopath() {
+	if [[ ! -d "${REPOPATH}" ]]; then
+		echo "Can't find ${REPOPATH}. Please edit and set '\$REPOPATH' variable in script."
+		exit 1
+	fi
+}
 
 sync () {
 	check_mirror
@@ -113,6 +131,8 @@ while [ "$1" != "" ]; do
 		-s | --sync )	
 				shift
 				export ARCH=$1
+				check_wget
+				check_repopath
 				get_arch
 				sync
 				;;
@@ -120,10 +140,12 @@ while [ "$1" != "" ]; do
 				shift
 				LINK=$1
 				NPATH=$2
+				check_repopath
 				update
 				shift
 				;;
-		-l | --list )	list_repo	
+		-l | --list )	check_repopath
+				list_repo	
 				;;
 		-h | --help ) 	usage
 				exit 
